version: "3.8"

services:
  backend:
    image: revic2112/dev-analisis-backend:latest # Imagen publicada en Docker Hub
    container_name: backend
    restart: always
    ports:
      - "5035:5035" # Puerto expuesto por tu aplicación
    depends_on:
      - sqlserver
    networks:
      - backend

  frontend:
    image: revic2112/dev-analisis-front:latest # Imagen publicada en Docker Hub
    container_name: frontend
    restart: always
    ports:
      - "4200:80" # Puerto expuesto por tu aplicación
    depends_on:
      - backend
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./script:/scripts
    entrypoint: /bin/bash -c "sleep 15; /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong!Passw0rd -i /scripts/init.sql"
    networks:
      - backend

volumes:
  sql_data:


networks:
  backend:
