version: "3.8"

services:
  backend:
    image: revic2112/dev-analisis-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5035:5035"
    depends_on:
      - sqlserver
    networks:
      - backend

  frontend:
    image: revic2112/dev-analisis-front:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 4g

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./script:/scripts
    entrypoint: /bin/bash -c "sleep 15; /mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong!Passw0rd -i /init.sql"
    networks:
      - backend

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /path/to/letsencrypt:/letsencrypt
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - frontend
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    command: certonly --webroot --webroot-path=/letsencrypt -d proy-analisis-re2112.duckdns.org --email tu-email@example.com --agree-tos --non-interactive

volumes:
  sql_data:
  certs:
  certs-data:


networks:
  backend:
